# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pctl < Formula
  desc "Command Line Interface tool for Paralus"
  homepage "https://github.com/paralus/cli"
  version "0.0.6"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/rustiever/cli/releases/download/v0.0.6/cli_0.0.6_darwin_all.tar.gz"
    sha256 "2d9f59aa226ea8904bf496760ad29cfc58f8acf692cb017e38098001cf9d8fa0"

    def install
      bin.install "cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rustiever/cli/releases/download/v0.0.6/cli_0.0.6_linux_amd64.tar.gz"
      sha256 "cf680096f8c943a76708b864b1950cd0e1785132762fdbb6e21720f5c332fa10"

      def install
        bin.install "pctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rustiever/cli/releases/download/v0.0.6/cli_0.0.6_linux_arm64.tar.gz"
      sha256 "67bc92a90ce33e904e09441f2c8b9ee3fbe72566963494453606939c1d19f1fa"

      def install
        bin.install "pctl"
      end
    end
  end
end
